[theme]
base = "light"

# Colors
primaryColor = "#111440"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#111440"

# Widgets
showWidgetBorder = true
borderColor = "#111440"

# Dataframes
dataframeHeaderBackgroundColor = "#F0F2F6"

[server]
enableCORS = false